version: 2

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      
      # login
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      
      # build content container
      - run: docker build -t openneuro/content .

      # push content container
      - run:
          name: docker tag + push (tag)
          command: |
            if [ "${CIRCLE_TAG}" ]; then
              docker tag openneuro/server "openneuro/server:${CIRCLE_TAG}"
              docker push "openneuro/server:${CIRCLE_TAG}"
            fi
            if [ -z "${CIRCLE_TAG}" ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag openneuro/server openneuro/server:latest
              docker push openneuro/server
            fi


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
